### ISSUE TITLE
Quantified tails

### ISSUE THREAD

**Issue by AdrienChampion** [chc-comp/llreve-bench#3]
The following benchmarks produce errors of the form

```
Illegal i_formula: only ground expressions are allowed
```

This comes from quantifiers appearing in the clauses' tail.

- [`smt2/arrays/heap__swaparray.array.smt2`](https://github.com/chc-comp/llreve-bench/tree/master/smt2/arrays/heap__swaparray.array.smt2)
- [`smt2/arrays/libc__strcspn_2.array.smt2`](https://github.com/chc-comp/llreve-bench/tree/master/smt2/arrays/libc__strcspn_2.array.smt2)
- [`smt2/arrays/libc__strcspn_3.array.smt2`](https://github.com/chc-comp/llreve-bench/tree/master/smt2/arrays/libc__strcspn_3.array.smt2)
- [`smt2/quant/coreutils__remove.smt2`](https://github.com/chc-comp/llreve-bench/tree/master/smt2/quant/coreutils__remove.smt2)
- [`smt2/arrays/coreutils__remove.array.smt2`](https://github.com/chc-comp/llreve-bench/tree/master/smt2/arrays/coreutils__remove.array.smt2)

**Comment by agurfinkel** [comment]
Note that these are arrays and quantifier examples. They probably don't fit the format by intention. Closing this for now since this year we are not supporting anything other than arithmetic.

**Comment by AdrienChampion** [comment]
As discussed separately, the actual benchmarks we should use are the `.muz` ones, which do not pose any problem.

**Comment by agurfinkel** [comment]
It's not that simple. Initial submission by @mattulbrich contained every benchmark in both formats. However, he subsequently improved the `smt2` benchmarks. It is possible we have some benchmarks of interest in `smt2` only format. Hopefully @mattulbrich is notified about his name being used in a comment and will suggest what to do :)

**Comment by mattulbrich** [comment]
I think every benchmark can also be muztified. I can classify the data there accordingly, too. (See question in #1.)
